/* List of important colours with their names and hexacode
Collected from different websites (flat-ui and material-ui)
*/
export default [
    {
      paletteName: "Colors collection 1",
      id: "colors-collection-1",
      emoji: "1️⃣",
      colors: [
        { name: "yellow", color: "#FFEB3B" },
        { name: "pink", color: "#E91E63" },
        { name: "lightgreen", color: "#8BC34A" },
        { name: "lightblue", color: "#03A9F4" },
        { name: "brown", color: "#795548" },
        { name: "indigo", color: "#3F51B5" },
        { name: "amber", color: "#FFC107" },
        { name: "cyan", color: "#00BCD4" },
        { name: "deeppurple", color: "#673AB7" },
        { name: "green", color: "#4CAF50" },
        { name: "purple", color: "#9C27B0" },
        { name: "bluegrey", color: "#607D8B" },
        { name: "blue", color: "#2196F3" },
        { name: "lime", color: "#CDDC39" },
        { name: "grey", color: "#9E9E9E" },
        { name: "red", color: "#F44336" },
        { name: "orange", color: "#FF9800" },
        { name: "deeporange", color: "#FF5722" },
        { name: "teal", color: "#009688" }
      ]
    },
    {
      paletteName: "Colors collection 2",
      id: "colors-collection-2",
      emoji: "2️⃣",
      colors: [
        { name: "SunFlower", color: "#f1c40f" },
        { name: "BelizeHole", color: "#2980b9" },
        { name: "Pomegranate", color: "#c0392b" },
        { name: "WetAsphalt", color: "#34495e" },
        { name: "Asbestos", color: "#7f8c8d" },
        { name: "Nephritis", color: "#27ae60" },
        { name: "Turquoise", color: "#1abc9c" },
        { name: "Pumpkin", color: "#d35400" },
        { name: "Amethyst", color: "#9b59b6" },
        { name: "Alizarin", color: "#e74c3c" },
        { name: "Wisteria", color: "#8e44ad" },
        { name: "Clouds", color: "#ecf0f1" },
        { name: "Orange", color: "#f39c12" },
        { name: "Concrete", color: "#95a5a6" },
        { name: "MidnightBlue", color: "#2c3e50" },
        { name: "GreenSea", color: "#16a085" },
        { name: "Emerald", color: "#2ecc71" },
        { name: "Silver", color: "#bdc3c7" },
        { name: "PeterRiver", color: "#3498db" },
        { name: "Carrot", color: "#e67e22" }
      ]
    },
    {
      paletteName: "Colors collection 3",
      id: "colors-collection-3",
      emoji: "3️⃣",
      colors: [
        { name: "CircumorbitalRing", color: "#5758BB" },
        { name: "BaraRose", color: "#ED4C67" },
        { name: "AndroidGreen", color: "#A3CB38" },
        { name: "Energos", color: "#C4E538" },
        { name: "RadiantYellow", color: "#F79F1F" },
        { name: "20000LeaguesUnderTheSea", color: "#1B1464" },
        { name: "PuffinsBill", color: "#EE5A24" },
        { name: "MerchantMarineBlue", color: "#0652DD" },
        { name: "RedPigment", color: "#EA2027" },
        { name: "ForgottenPurple", color: "#9980FA" },
        { name: "LavenderTea", color: "#D980FA" },
        { name: "HollyHock", color: "#833471" },
        { name: "MagentaPurple", color: "#6F1E51" },
        { name: "VerryBerry", color: "#B53471" },
        { name: "BlueMartina", color: "#12CBC4" },
        { name: "Sunflower", color: "#FFC312" },
        { name: "TurkishAqua", color: "#006266" },
        { name: "MediterraneanSea", color: "#1289A7" },
        { name: "PixelatedGrass", color: "#009432" },
        { name: "LavenderRose", color: "#FDA7DF" }
      ]
    },
    {
      paletteName: "Colors collection 4",
      id: "colors-collection-4",
      emoji: "4️⃣",
      colors: [
        { name: "BrightYarrow", color: "#fdcb6e" },
        { name: "SoothingBreeze", color: "#b2bec3" },
        { name: "CityLights", color: "#dfe6e9" },
        { name: "DraculaOrchid", color: "#2d3436" },
        { name: "FadedPoster", color: "#81ecec" },
        { name: "Pico8Pink", color: "#fd79a8" },
        { name: "RobinsEggBlue", color: "#00cec9" },
        { name: "FirstDate", color: "#fab1a0" },
        { name: "PrunusAvium", color: "#e84393" },
        { name: "ShyMoment", color: "#a29bfe" },
        { name: "MintLeaf", color: "#00b894" },
        { name: "Chi-Gong", color: "#d63031" },
        { name: "ElectronBlue", color: "#0984e3" },
        { name: "OrangeVille", color: "#e17055" },
        { name: "AmericanRiver", color: "#636e72" },
        { name: "ExodusFruit", color: "#6c5ce7" },
        { name: "SourLemon", color: "#ffeaa7" },
        { name: "PinkGlamour", color: "#ff7675" },
        { name: "LightGreenishBlue", color: "#55efc4" },
        { name: "GreenDarnerTail", color: "#74b9ff" }
      ]
    },
    {
      paletteName: "Colors collection 5",
      id: "colors-collection-5",
      emoji: "5️⃣",
      colors: [
        { name: "SteelPink", color: "#be2edd" },
        { name: "SoaringEagle", color: "#95afc0" },
        { name: "GreenlandGreen", color: "#22a6b3" },
        { name: "PureApple", color: "#6ab04c" },
        { name: "Turbo", color: "#f9ca24" },
        { name: "Blurple", color: "#4834d4" },
        { name: "SpicedNectarine", color: "#ffbe76" },
        { name: "DeepKoamaru", color: "#30336b" },
        { name: "MiddleBlue", color: "#7ed6df" },
        { name: "DeepCove", color: "#130f40" },
        { name: "ExodusFruit", color: "#686de0" },
        { name: "WizardGrey", color: "#535c68" },
        { name: "JuneBud", color: "#badc58" },
        { name: "CoastalBreeze", color: "#dff9fb" },
        { name: "CarminePink", color: "#eb4d4b" },
        { name: "Heliotrope", color: "#e056fd" },
        { name: "Beekeeper", color: "#f6e58d" },
        { name: "PinkGlamour", color: "#ff7979" },
        { name: "QuinceJelly", color: "#f0932b" },
        { name: "HintOfIcePack", color: "#c7ecee" }
      ]
    },
    {
      paletteName: "Colors collection 6",
      id: "colors-collection-6",
      emoji: "6️⃣",
      colors: [
        { name: "Periwinkle", color: "#9c88ff" },
        { name: "Rise-N-Shine", color: "#fbc531" },
        { name: "DownloadProgress", color: "#4cd137" },
        { name: "PicoVoid", color: "#192a56" },
        { name: "VanaDylBlue", color: "#0097e6" },
        { name: "HintOfPensive", color: "#dcdde1" },
        { name: "BlueberrySoda", color: "#7f8fa6" },
        { name: "Naval", color: "#40739e" },
        { name: "MattPurple", color: "#8c7ae6" },
        { name: "Seabrook", color: "#487eb0" },
        { name: "SkirretGreen", color: "#44bd32" },
        { name: "MazarineBlue", color: "#273c75" },
        { name: "NanohanachaGold", color: "#e1b12c" },
        { name: "HarleyOrange", color: "#c23616" },
        { name: "ProtossPylon", color: "#00a8ff" },
        { name: "BlueNights", color: "#353b48" },
        { name: "ElectroMagnetic", color: "#2f3640" },
        { name: "ChainGangGrey", color: "#718093" },
        { name: "NasturcianFlower", color: "#e84118" },
        { name: "LynxWhite", color: "#f5f6fa" }
      ]
    },
    {
      paletteName: "Colors collection 7",
      id: "colors-collection-7",
      emoji: "7️⃣",
      colors: [
        { name: "SummerSky", color: "#34ace0" },
        { name: "ChileanFire", color: "#cd6133" },
        { name: "SwanWhite", color: "#f7f1e3" },
        { name: "CrocodileTooth", color: "#d1ccc0" },
        { name: "MandarinSorbet", color: "#ffb142" },
        { name: "LuckyPoint", color: "#2c2c54" },
        { name: "C64Purple", color: "#706fd3" },
        { name: "JacksonsPurple", color: "#40407a" },
        { name: "Desert", color: "#ccae62" },
        { name: "Liberty", color: "#474787" },
        { name: "FlourescentRed", color: "#ff5252" },
        { name: "GreyPorcelain", color: "#84817a" },
        { name: "PalmSpringsSplash", color: "#218c74" },
        { name: "AlamedaOchre", color: "#cc8e35" },
        { name: "DevilBlue", color: "#227093" },
        { name: "SyntheticPumpkin", color: "#ff793f" },
        { name: "HotStone", color: "#aaa69d" },
        { name: "SpicedButterNut", color: "#ffda79" },
        { name: "CelestialGreen", color: "#33d9b2" },
        { name: "EyeOfNewt", color: "#b33939" }
      ]
    },
    {
      paletteName: "Colors collection 8",
      id: "colors-collection-8",
      emoji: "8️⃣",
      colors: [
        { name: "OrchidOrange", color: "#FEA47F" },
        { name: "PineGlade", color: "#BDC581" },
        { name: "FallingStar", color: "#CAD3C8" },
        { name: "Keppel", color: "#58B19F" },
        { name: "HighlighterLavender", color: "#82589F" },
        { name: "WhitePepper", color: "#F8EFBA" },
        { name: "MagentaPurple", color: "#6D214F" },
        { name: "BrightUbe", color: "#D6A2E8" },
        { name: "FieryFuchsia", color: "#B33771" },
        { name: "OasisStream", color: "#9AECDB" },
        { name: "HoneyGlow", color: "#EAB543" },
        { name: "EndingNavyBlue", color: "#182C61" },
        { name: "SweetGarden", color: "#55E6C1" },
        { name: "BlueBell", color: "#3B3B98" },
        { name: "ShipsOfficer", color: "#2C3A47" },
        { name: "ClearChill", color: "#1B9CFC" },
        { name: "SpiroDiscoBall", color: "#25CCF7" },
        { name: "GeorgiaPeach", color: "#FD7272" },
        { name: "RichGardenia", color: "#F97F51" },
        { name: "SasquatchSocks", color: "#FC427B" }

      ]
    },
    {
      paletteName: "Colors collection 9",
      id: "colors-collection-9",
      emoji: "9️⃣",
      colors: [
        { name: "MandarinRed", color: "#e55039" },
        { name: "CarrotOrange", color: "#e58e26" },
        { name: "Waterfall", color: "#38ada9" },
        { name: "ForestBlues", color: "#0a3d62" },
        { name: "ParadiseGreen", color: "#b8e994" },
        { name: "IcelandPoppy", color: "#fa983a" },
        { name: "JalapenoRed", color: "#b71540" },
        { name: "Livid", color: "#6a89cc" },
        { name: "ReefEncounter", color: "#079992" },
        { name: "MelonMelody", color: "#f8c291" },
        { name: "GoodSamaritan", color: "#3c6382" },
        { name: "SquashBlossom", color: "#f6b93b" },
        { name: "TomatoRed", color: "#eb2f06" },
        { name: "DarkSapphire", color: "#0c2461" },
        { name: "FlatFlesh", color: "#fad390" },
        { name: "AuroraGreen", color: "#78e08f" },
        { name: "AzraqBlue", color: "#4a69bd" },
        { name: "Dupain", color: "#60a3bc" },
        { name: "Spray", color: "#82ccdd" },
        { name: "YueGuangBlue", color: "#1e3799" }
      ]
    }
  ];